name: Deploy to EKS (Kubernetes)

on:
  push:
    branches:
      - main
    paths:
      - 'deployments/**'
      - 'kubernetes/**'
      - 'services/**'
      - 'ingress/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # ajuste conforme sua região

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name nome-do-cluster --region us-east-1

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployments/
          kubectl apply -f services/
          kubectl apply -f ingress/
          kubectl apply -f kubernetes/
